version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "Dependency"
      include: "scope"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "Dependency"
      include: "scope"
