version: "2"
services:
  bot:
    # entrypoint: /bin/sh -c
    container_name: bot
    restart: always
    build: .
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "production_status"
        env: "os"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ~/data:/data/db
    ports:
      - "44839:27017"
