version: "2"
services:
  bot:
    # entrypoint: /bin/sh -c
    container_name: bot
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ~/data:/data/db
    ports:
      - "27017:27017"
