version: "2"
services:
  bot:
    container_name: bot
    restart: always
    build: .
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "production_status"
        env: "os"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.4.8-rc0-focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor # change this while running!
    restart: always
    volumes:
      - ~/docker_mongodb_data:/data/db
    ports:
      - "27017:27017"
    command: [--auth]
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "production_status"
        env: "os"
